### PR TITLE
Installation instructions for yarn were added

### PR DESCRIPTION
**Pull request by MAPESO**
For users who use yarn :]

### CODE REVIEW

**Comment by MAPESO** [comment]
@pavelfeldman  For some strange reason my PR is failing. Appears and disappears from the repo de carlo

**Comment by MAPESO** [comment]
@pavelfeldman I return to open the PR ^-^

**Comment by MAPESO** [comment]
@pavelfeldman I just deleted `yarn.lock`

**Comment by pavelfeldman** [comment]
Could you sign cla/google as the bot suggests?

**Pull request merged**
