### PR TITLE
Serve files from filesystem and wwwOrigin

### PR DESCRIPTION
**Pull request by vladimir-shilin**
I need to serve application from wwwOrigin in development mode, but app need to have access to filesystem.
At first this code searches files by prefixes in filesystem, then tries to get it from wwwOrigin.
Also there is fix which converts url to path for searching in filesystem with `decodeURIComponent` function.

### CODE REVIEW

**Comment by vladimir-shilin** [comment]
I signed it!

**Comment by pavelfeldman** [comment]
I've seen the opposite requests as well where dev workflow was supposed to override the locally available files. I.e. order matters. I wonder if we should deprecate `serveOrigin` in favor of a smarter `serveFolder`:

```js
app.serveFolder('http://localhost', 'prefix');
app.serveFolder('www');
```

These would be matched in the specified order. Would that work for you?

**Comment by vladimir-shilin** [comment]
Yes. That would be great.

**Comment by pavelfeldman** [comment]
Do you want to do it or should I?

**Comment by vladimir-shilin** [comment]
I can try.

**Comment by pavelfeldman** [comment]
Sounds good! I was thinking of keeping `serveOrigin` for backwards compat:

```js
serveOrigin(origin) {
  this.serveFolder(origin);
}
```

and then in the `for (const [prefix, folders] of this.www_)` loop detect those that are origins and serve files respectively. We can assume that serving from the origin always succeeds.

**Comment by vladimir-shilin** [comment]
I see the problem that search of file will stop at first folder which is url. I think we need make request in that case and check response code. Can I use some library for that or use node `http` and `https` libraries instead?

**Comment by pavelfeldman** [comment]
I thought your `prefix` was sufficient to match deterministically. Could you paste your filsystem structure and which files you would like to serve over http for me to understand it better?

**Comment by vladimir-shilin** [comment]
In my case I'll have index.html and app.js on `http://locahost` and other files in filesystem by prefixes. For example `app.serveFolder('http://locahost'); app.serveFolder('somefolder/images', 'images');`
Even in this case request `/images/1.jpg` will match prefix `''` and get 404 error.

**Comment by pavelfeldman** [comment]
This would do what you want though, right? (Order matters)

```js
app.serveFolder('somefolder/images', 'images');
app.serveFolder('http://locahost');
```

**Comment by vladimir-shilin** [comment]
Not exactly. At first app opens, then user choose folder with images.

**Comment by pavelfeldman** [comment]
Got it. Let me take it offline. You might need manual request interception to resolve this. I was planning on adding it anyways.

**Comment by vladimir-shilin** [comment]
Thanks. Good luck!

**Pull request closed without merging**
